frameworkVersion: "^2.1.0"

service: ${self:custom.productPhotos.successName}

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  productPhotos: ${file(../productPhotos.yml)}

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs12.x
  region: ${self:custom.private.region}
  tracing:
    apiGateway: true
    lambda: true

functions:
  success:
    role:
      'Fn::GetAtt': [ SuccessRole, Arn ]
    handler: success.handler
    memorySize: 1024

resources:
  Resources:
    # Log Group
    SuccessLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/${self:service}-${self:custom.stage}-success'
        RetentionInDays: 7
    # Role
    SuccessRole: # role for the assignment succeeding lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.stage}ProductPhotosSuccess${self:custom.productPhotos.productPhotosVersion}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
          # Lambda execution role permissions for XRay: https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html#services-xray-permissions
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ SuccessLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ SuccessLogGroup, Arn ]
                        - '*'
  Outputs:
    SuccessLambdaName:
      Description: The Name of the Photo Assignments Success Lambda
      Value:
        Ref: SuccessLambdaFunction
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsSuccessLambdaName}
    SuccessLambdaArn:
      Description: The Name of the Photo Assignments Success Lambda
      Value:
        'Fn::GetAtt': [ SuccessLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsSuccessLambdaArn}
