service: cpustress

frameworkVersion: '>=2.0.0 <3.0.0'

provider:
  name: google
  runtime: nodejs
  project: ${opt:project, 'faastest-268812'}
  credentials: ${opt:credentials, '/tmp/.gcloud/faasbenchmark.json'}
  region: ${opt:region, 'europe-west1'}

functions:
  google-cpustress-nodejs:
    runtime: nodejs10
    handler: main
    memorySize: 512
    timeout: 120s
    events:
      - http: path

package:
  exclude:
    - ./**
  include:
    - ./index.js

plugins:
  - serverless-google-cloudfunctions
